apiVersion: v1
kind: Service
metadata:
  name: Demo
  namespace: namespace-workflow-1685610716580
spec:
  type: LoadBalancer
  selector:
    app: Demo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000